### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by darshancc23** [darshancc23/RESTful-apps#2]
Need to improve the documentation. You can add screenshots, explain about the project, etc.

To set up the project in your local machine follow the steps in the [README.md](https://github.com/darshancc23/RESTful-apps/blob/master/blog-app/README.md) file.

**Make sure you edit the README.md file inside the blog-app directory.**

**Comment by RootPixl** [comment]
Can I do this?

**Comment by RootPixl** [comment]
check my PR
